name: Submit a Doubt
description: Post your GATE doubt. Select subject, describe your question, and optionally include an image by dragging it into the description. The issue will be labeled with the chosen subject automatically.
title: ""
# labels: ["New Doubt"]
body:
      
  - type: markdown
    attributes:
      value: |
      🚨 **NOTE:** PLEASE ADD THE APPROPRIATE LABEL `subject: ...` LABEL (E.G., `subject: TOC`, `subject: DBMS`, ETC.) SO OTHERS CAN FILTER ANSWER DOUBT EASILY.
  # - type: input
  #   id: short-description
  #   attributes:
  #     label: Brief summary (used in title)
  #     placeholder: e.g., “Is language regular if...?”
  #   validations:
  #     required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Explain your doubt clearly. You can drag & drop or paste images directly here. 
    validations:
      required: true
