name: Submit a Doubt
description: Post your GATE doubt. Describe your question, add labels, and optionally include an image by dragging it into the description.
title: "Add a title"
# labels: ["New Doubt"]
body:
  - type: dropdown
    id: Subject
    attributes:
      label: Subject
      options:
        - TOC
        - CD
        - CN
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Explain your doubt clearly. You can drag & drop or paste images directly here. 
    validations:
      required: true
