name: Auto Label from Subject

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  add-label-from-subject:
    runs-on: ubuntu-latest
    steps:
      - name: Extract subject from issue body
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";

            // Find "Subject" field from GitHub Issue Form
            const match = body.match(/### Subject\s*\n(.*)/i);
            core.info(`match value is:`, match);
            if (!match || !match[1]) {
              core.info("No subject found in the issue form.");
              core.setOutput("label", "");
              return;
            }

            const subjectValue = match[1].trim();
            core.info(`Detected subject: ${subjectValue}`);

            // Mapping from dropdown value → label name in repo
            // LHS : Dropdown Values
            // RHS : Labels in the repo
            const labelMap = {
              "TOC": "TOC",
              "CD": "CD",
              "CN": "CN"
            };

            if (labelMap[subjectValue]) {
              core.setOutput("label", labelMap[subjectValue]);
            } else {
              core.info(`No label mapping found for: ${subjectValue}`);
              core.setOutput("label", "");
            }

      - name: Add label to the issue
        if: steps.extract.outputs.label != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.extract.outputs.label }}
